### ISSUE TITLE
Unable to start daemon on Redmi Note 13 (sapphiren) V14.0.5.0.TNHTWXM

### ISSUE THREAD

**Issue by sabpprook** [5ec1cff/TrickyStore#69]
![2024-09-15 160102](https://github.com/user-attachments/assets/17b1f41d-70f1-4b7b-8ddf-4e6ab1793dcd)
![2024-09-15 160117](https://github.com/user-attachments/assets/c48dee62-178f-4e6b-b660-f03c9d547d69)

```
sapphiren:/data/adb/modules/tricky_store # ls -l
total 2801
-rwxr-xr-x 1 root root     146 2024-09-15 15:52 daemon
-rw-r--r-- 1 root root  720400 2024-09-15 15:52 libtricky_store.so
-rw-r--r-- 1 root root      96 2024-09-15 15:52 machikado
-rw-r--r-- 1 root root      96 2024-09-15 15:52 mazoku
-rw-r--r-- 1 root root     237 2024-09-15 15:53 module.prop
-rw-r--r-- 1 root root      15 2024-09-15 15:52 post-fs-data.sh
-rw-r--r-- 1 root root     164 2024-09-15 15:52 sepolicy.rule
-rw-r--r-- 1 root root 2130642 2024-09-15 15:52 service.apk
-rw-r--r-- 1 root root     164 2024-09-15 15:52 service.sh
sapphiren:/data/adb/modules/tricky_store # sh daemon
java.io.FileNotFoundException: /data/system/theme_config/theme_compatibility.xml: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:574)
        at java.io.FileInputStream.<init>(FileInputStream.java:160)
        at java.io.FileInputStream.<init>(FileInputStream.java:115)
        at java.io.FileReader.<init>(FileReader.java:60)
        at miui.content.res.ThemeCompatibilityLoader.getVersion(ThemeCompatibilityLoader.java:108)
        at miui.content.res.ThemeCompatibilityLoader.getConfigDocumentTree(ThemeCompatibilityLoader.java:126)
        at miui.content.res.ThemeCompatibilityLoader.loadConfig(ThemeCompatibilityLoader.java:59)
        at miui.content.res.ThemeCompatibility.<clinit>(ThemeCompatibility.java:31)
        at android.content.res.MiuiResourcesImpl.<clinit>(MiuiResourcesImpl.java:41)
        at android.content.res.MiuiResources.<init>(MiuiResources.java:58)
        at android.content.res.IMiuiResourceImpl.createResources(IMiuiResourceImpl.java:13)
        at android.content.res.ThemeManagerStub.createMiuiResources(ThemeManagerStub.java:56)
        at android.content.res.Resources.getSystem(Resources.java:251)
        at android.app.ActivityManager.isHighEndGfx(ActivityManager.java:1224)
        at android.view.ThreadedRenderer.initForSystemProcess(ThreadedRenderer.java:222)
        at android.app.ActivityThread.systemMain(ActivityThread.java:8191)
        at io.github.a13e300.tricky_store.MainKt.main(Unknown Source:25)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:367)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
        at libcore.io.IoBridge.open(IoBridge.java:560)
        ... 18 more
android.system.ErrnoException: open failed: ENOENT (No such file or directory)
        at libcore.io.Linux.open(Native Method)
        at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
        at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
        at android.system.Os.open(Os.java:494)
        at android.os.perfdebug.PerfDebugMonitorImpl.monitorVersionControl(PerfDebugMonitorImpl.java:204)
        at android.os.perfdebug.PerfDebugMonitorImpl.prepareMonitor(PerfDebugMonitorImpl.java:185)
        at android.app.ActivityThread.systemMain(ActivityThread.java:8193)
        at io.github.a13e300.tricky_store.MainKt.main(Unknown Source:25)
        at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
        at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:367)
```

**Comment by sabpprook** [comment]
But tricky store 1.1.2 will work

![2024-09-15 160821](https://github.com/user-attachments/assets/6f4e4ac2-33b8-4975-9eb6-aac8de67cae6)
![2024-09-15 160849](https://github.com/user-attachments/assets/d04414c2-946e-4be2-83c2-72836791dc18)

**Comment by aviraxp** [comment]
That is not caused by the log posted, try use 1.2.0 RC1

**Comment by sabpprook** [comment]
okay, I'm just curious why the file be accessed by trickystore. I'll keep on using v1.1.2
