### ISSUE TITLE
TrickyStore not work for me

### ISSUE THREAD

**Issue by kaisar945** [5ec1cff/TrickyStore#77]
Device: OnePlus 12
Android Version: 14
Installed Magisk modules:
1. Play Integrity Fix v17.7  disabled
2. Shamiko v1.1 enabled
3. Tricky Store v1.2.0-RC2 enabled
4. Zygisk - LSPosed v1.9.2 enabled

Logcat
```
--------- beginning of main
10-18 20:06:29.290  3167  3167 I TrickyStore: Welcome to TrickyStore!
10-18 20:06:29.290  3167  3167 I TrickyStore: Trying to register keystore interceptor ...
10-18 20:06:29.290  3167  3167 I TrickyStore: waiting for service package
10-18 20:06:33.292  3167  3167 I TrickyStore: waiting for service android.system.keystore2.IKeystoreService/default
10-18 20:06:35.683  3167  3167 E TrickyStore: test tee broken (strong=false)
10-18 20:06:35.683  3167  3167 E TrickyStore: java.security.ProviderException: Failed to generate key pair.
10-18 20:06:35.683  3167  3167 E TrickyStore: 	at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:664)
10-18 20:06:35.683  3167  3167 E TrickyStore: 	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:746)
10-18 20:06:35.683  3167  3167 E TrickyStore: 	at io.github.a13e300.tricky_store.MainKt.main(Unknown Source:438)
10-18 20:06:35.683  3167  3167 E TrickyStore: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
10-18 20:06:35.683  3167  3167 E TrickyStore: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:379)
10-18 20:06:35.683  3167  3167 E TrickyStore: Caused by: android.security.KeyStoreException: -49 (internal Keystore code: -49 message: system/security/keystore2/src/security_level.rs:626
10-18 20:06:35.683  3167  3167 E TrickyStore: 
10-18 20:06:35.683  3167  3167 E TrickyStore: Caused by:
10-18 20:06:35.683  3167  3167 E TrickyStore:     0: system/security/keystore2/src/security_level.rs:624: While generating Key without explicit attestation key.
10-18 20:06:35.683  3167  3167 E TrickyStore:     1: Error::Km(r#SECURE_HW_COMMUNICATION_FAILED)) (public error code: 10 internal Keystore code: -49)
10-18 20:06:35.683  3167  3167 E TrickyStore: 	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:386)
10-18 20:06:35.683  3167  3167 E TrickyStore: 	at android.security.KeyStoreSecurityLevel.handleExceptions(KeyStoreSecurityLevel.java:57)
10-18 20:06:35.683  3167  3167 E TrickyStore: 	at android.security.KeyStoreSecurityLevel.generateKey(KeyStoreSecurityLevel.java:145)
10-18 20:06:35.683  3167  3167 E TrickyStore: 	at android.security.keystore2.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:651)
10-18 20:06:35.683  3167  3167 E TrickyStore: 	... 4 more
10-18 20:06:35.692  3167  3167 I TrickyStore: teeBroken=true
10-18 20:06:35.697  3167  3167 I TrickyStore: trying to inject keystore ...
10-18 20:06:35.698  3167  3167 I TrickyStore: injecting /data/adb/modules/tricky_store/libtricky_store.so and calling entry in 1141
10-18 20:06:35.705  3167  3167 E TrickyStore: send to remote failed with 13: Permission denied
10-18 20:06:35.705  3167  3167 E TrickyStore: setregs failed with 3: No such process
10-18 20:06:35.705  3167  3167 E TrickyStore: failed to set regs
10-18 20:06:35.706  3167  3167 E TrickyStore: failed to inject! daemon exit
```

Do I need to provide anything else?

**Comment by aviraxp** [comment]
Your keystore process died for other reasons. Check for full log.

**Comment by kaisar945** [comment]
> Your keystore process died for other reasons. Check for full log.

How to get the full log? I think it might be easier to report issues if this is stated in the README.

**Comment by 5ec1cff** [comment]
It should be work in 1.2.0
